### ISSUE TITLE
Support for Labels

### ISSUE THREAD

**Issue by JohanPotgieter** [bogenpirat/remote-torrent-adder#167]
This is not a bug but a suggestion that would make the plug-in more useful for those of use that applications like Sonarr. Deluge can have labels assigned to downloading items that help sonarr to track these items. If there can be a setup for the label within the deluge setup it would save me the trouble of doing into deluge after adding a torrent to update the label. I know this may not be what everyone wants as some torrents you may not want sonarr to manage. In my case almost all of the torrent that I download is because sonarr has not found them via it's rss feeds.

Would be a nice option to have for those who wants to use it, like me...

Great plugin...

**Comment by bogenpirat** [comment]
labels are kind of a sore issue for me personally.

i added support for them in rutorrent because it was pretty straight forward, but using them isn't really super easy and sorta goes against the philosophy of the extension in that it requires an additional couple of clicks and potentially additional keystrokes which i'm really not fond of.

so for now i'm not committing to adding this issue. pull requests are however very welcome.
