### ISSUE TITLE
Test a connection

### ISSUE THREAD

**Issue by lbarnett83** [bogenpirat/remote-torrent-adder#170]
Recently, my RTA extension has not been sending torrents to my remote server.  I know that I have the info input correctly, but am still unsure of where the issue lies.  One thing that I think would be a good idea, is to add a "Test" button to spot where you are adding a server, since Then you know if RTA is getting a connection to the remote server.  Right now, when I try and add a torrent, nothing happens at all, no popup, and the torrent never appears in my remote instance of deluge,  Any ideas on how to fix this would be appreciated :)

**Comment by bogenpirat** [comment]
there's just no good way of implementing this for the 10+ clients that the extension supports.

even if we leave aside clients like rutorrent that come in about twenty bajillion different configurations because their setup depends on the web servers they run on, there's still issues like connection timeouts, read/write timeouts, weird client-specific quirks where they might reject data, encryption/certificate nonsense, different ways of rejecting authentication, etc.

as far as i know, *none* of the clients support any sort of dedicated test call to verify that api access, let alone torrent adding is working. you'd have to go and add an actual torrent, and that's just not feasible. the (admittedly quite laconic and techy) error output that you get right now is more or less the best i can get you.

as a rule of thumb, if you're able to open the web ui in your browser manually and that works without any additional confirmation steps on your part, then RTA should work fine unless you misconfigure it.

if you don't get any confirmation/error message at all, i suggest that you snapshot the background page view from the extension overview page in chrome and open a new issue with a more fitting title that lets me address your particular issue.

a general test function is a no-go from where i'm sitting.
