### ISSUE TITLE
Support for HTTP Basic authentication

### ISSUE THREAD

**Issue by buzz** [bogenpirat/remote-torrent-adder#175]
I use _basic HTTP authentication_ to secure my torrent web front-end. Remote torrent adder only works for me if I manually enter username + password before clicking a torrent link.

Would it be hard to implement support for HTTP basic auth? I would also contribute a PR.

**Comment by bogenpirat** [comment]
authentication is handled on a per-client basis. that means that if you use, for instance, transmission, http basic auth is already being employed. the same is true for my implementation of the rutorrent module.

at this point it'd be useful to know what client you use. after that, we can figure out whether an additional authentication feature makes sense.

**Comment by buzz** [comment]
Hey, thanks for the reply.

I'm using *rutorrent*.

I couldn't figure out any RTA settings to make this work without entering credentials beforehand. (To be complete: A workaround to this is to safe the basic auth credentials with the browser).

**Comment by bogenpirat** [comment]
right, i was closing this because it had been inactive since october. 😉

as per this: https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/ruTorrentWebUI.js#L26
basic auth as well as digest auth should be fully supported as per chrome's own XHR functionality. in addition, my test setup as well as productive setup works just fine. i suspect it's got something to do with your setup, but i can't really think of any way of debugging this short of you bringing over your computer.

**Comment by buzz** [comment]
It's the same behaviour on different computers. I have a completely normal Basic Auth using nginx:

    auth_basic "restricted";
    auth_basic_user_file passwd_rutorrent;

So, nothing special, everything off-the-shelf…

**Comment by bogenpirat** [comment]
okay, then it probably isn't your clients, but your server/configuration. any chance i can take a look at that?

**Comment by buzz** [comment]
What exactly? The complete nginx configuration?

**Comment by bogenpirat** [comment]
i mean i'd have to recreate the conditions that lead you to failure, considering for a similar configuration (apache2, rutorrent) there's no problem with any of the functionality. ideally you'd just hand me your login and webif url under the promise i won't touch anything other than adding DSL distro images for testing, but if you want to go another route, that's fine by me.

**Comment by buzz** [comment]
I appreciate that you take the time looking into this. :+1:
But, I can't give out any passwords.

I tried to debug the HTTP request and it seems the response from nginx is missing a *Access-Control-Allow-Origin* header.

Just putting `add_header "Access-Control-Allow-Origin" "*";` doesn't seem to help. nginx doesn't complain about an unknown directive which it should in case the *ngx_http_headers_module* is not included.  Unfortunately right now, I don't have the time to investigate further.

The workaround letting Chrome save the credentials is working for me at the moment.

**Comment by bogenpirat** [comment]
i appreciate the situation.

it seems a bit weird to me that letting chrome store the credentials fixes the problem. seems like that's something that shouldn't help.

for reference, he's an anonymized screenshot of a successful add to my apache/rutorrent installation.

![image](https://cloud.githubusercontent.com/assets/1835496/23475094/a5e05bbc-feb6-11e6-9ec3-fa43653c30a4.png)

as a test, you could send your Authorization header's encoded data through https://www.base64decode.org to check if it encoded the credentials correctly.

**Comment by buzz** [comment]
Here's the failing request stemming from RTA:

http://i.imgur.com/eSFrFON.png

Here's the output of the debug request I created out of Chrome DevTools:

http://i.imgur.com/1QakeX3.png

> as a test, you could send your Authorization header's encoded data through https://www.base64decode.org to check if it encoded the credentials correctly.

Credentials are correct.

**Comment by bogenpirat** [comment]
any chance you have some paranoia-level extension like umatrix or something like that installed? looks like interference... as you can see from the source to the right on the second screen, that second error message doesn't originate in RTA.

**Comment by buzz** [comment]
Yep, interference it is!

I did the request from the New Tab Page (`local-ntp.html`). I assume when launching XHR from Extensions in Chrome CORS restrictions don't apply?

Anyway, I made another mistake when I tested RTA in a fresh Chrome. I have a script that launches a fresh Chrome profile but actually installs an ad blocker extension. Using a completely fresh Chrome it works now!

So it's my client or one of the extensions I use I guess. My bet it is uBlock Origin.

**Comment by bogenpirat** [comment]
cross origin permissions for background pages' XHRs are defined by an extension's [manifest](https://github.com/bogenpirat/remote-torrent-adder/blob/master/manifest.json#L8); since the destinations aren't known at initialization, i quite liberally request *://*/* - any path on any host under any protocol. that does however not cover chrome-internal pages and as a result, ad blockers or cookie managers for instance don't work on chrome:// pages.

i'm honestly a bit surprised RTA would even find a link on NTP (in another extension, you say?). anyway, this scenario is exhibiting all sorts of "special" behavior, including the workaround. good thing we went with screenshots. 😉

**Comment by buzz** [comment]
No, actually I just used the DevTools on the NTP to do the debugging. But anyway, doesn't matter really.

Solved! Thanks! :blush: 
Keep up the good work and see you around! :sparkles:
