### ISSUE TITLE
Extension breaks functionality of this particular page: https://mydeviceinfo.xfinity.com/

### ISSUE THREAD

**Issue by drichelson** [bogenpirat/remote-torrent-adder#178]
It looks like this awesome extension disables the zip code entry form here:
https://mydeviceinfo.xfinity.com/

I can repro this with all other extensions disabled.

Chrome details:

Google Chrome	54.0.2840.98 (Official Build) (64-bit)
Revision	8ee402c67ff2f8f7c746e56d3530b4dcec0709ad-refs/branch-heads/2840@{#829}
OS	Mac OS X 
JavaScript	V8 5.4.500.41
Flash	23.0.0.207
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

**Comment by bogenpirat** [comment]
okay, so what's happening here is that jQuery, which this extension injects into the website mostly for the visual styling of the label choosing dialog (ruTorrent), somehow breaks the site's rendering which then, as you describe, makes the input fields unselectable.

that's obviously not supposed to happen. since the inclusion of jquery was a lazy fix for implementing that modal dialog, i should probably go ahead and replace it with something lighter that doesn't use a library.

**Comment by bogenpirat** [comment]
404a211 fixes this with a light-weight reimplementation of the modal dialog. now if only i could get some ruTorrent people to test this before i release it into the wild...

**Comment by bogenpirat** [comment]
released with 1.2.8.
