### ISSUE TITLE
RTA does not grab torrents- its inconsistent

### ISSUE THREAD

**Issue by juicy11** [bogenpirat/remote-torrent-adder#185]
Have the strangest behavior on RTA. Open browser and first torrent is sent OK to box. Later try or a different on a different one, RTA does not grab and returns HTTP error like in screenshot. Can't be wrong box settings when it works once in a while. This has not been for long. have used RTA for months without any problems. chrome version is 57.0.2950.4. Any ideas whats wrong?

![error](https://cloud.githubusercontent.com/assets/24659547/21328100/fd792156-c63a-11e6-840d-eeecd4aa8fc4.jpg)

**Comment by bogenpirat** [comment]
nope, no clue. that kind of error usually implies it can't even contact the server, e.g. because there's a self-signed certificate that is rejected by the browser. is your box overloaded? a good rule of thumb is that if you can open and perfectly use the web ui in your browser, then, given a correct configuration, you should also have no trouble using the extension.
