### ISSUE TITLE
not connecting to utorrent

### ISSUE THREAD

**Issue by i420piate** [bogenpirat/remote-torrent-adder#187]
Was working just fine, I use RTA in conjunction with utorrent easy client. But now it's not working for magnet links on extratorrent.cc, the icon for extension is greyed out on 2 PCs I tried, however I can right click magnet icon on site and add the link just fine with RTA so I know connection to torrent client does in fact work. Sometimes after a reboot the first magnet link works as it should then the second one I click asks me to open windows store to find an app for magnet links, and continues to do so. Hope I described this well enough.

**Comment by bogenpirat** [comment]
i see the same problem here.

this occurs due to the fact that the content of their page is obfuscated and dynamically built via javascript (see the [source code](view-source:http://extratorrent.cc/)). this includes the links which is why at the time of the document having being loaded, RTA cannot find any torrent links (unless the extension's content script runs after the site's js, which should result in very unreliable behavior).

i can't really think of a solution to this problem that doesn't introduce other, greater issues with other sites. so for now i can't fix this.

**Comment by i420piate** [comment]
Thanks for replying at least
