### ISSUE TITLE
Extratorrent.cc link catching does not work

### ISSUE THREAD

**Issue by tomballgithub** [bogenpirat/remote-torrent-adder#193]
Torrent and Magnet links on the home page of extratorrent.cc do not work.  Torrent links try to download the file.  Magnet links do nothing.  This occurs with and without an ad blocker.  This occurs with and without incognito.  This occurs whether or not you are logged in.    

This used to work fine until 4+ weeks ago.  I am using chrome version 57.0.2987.74 beta (64-bit).  

The icon in the toolbar does not light up.  Sometimes if you poke around long enough into sub-pages of specific torrents, it will light up and work on that page but it's inconsistent

If you right-click and clik 'Add to WebUI' it works every time.

Any help would be appeciated...

**Comment by tomballgithub** [comment]
My extension is version 1.2.9 
![image](https://cloud.githubusercontent.com/assets/15407947/23444215/47d7c978-fdf9-11e6-9744-ae538b52ae04.png)

**Comment by tomballgithub** [comment]
I also did a fresh install of google chrome 56 portable.  The only extension was Remote Torrent Adder.  Behavior was the same (Torrent links try to download the file. Magnet links do nothing)

**Comment by bogenpirat** [comment]
this is a problem with that particular site. if you check the source code (ctrl+u) you'll see that the code for the right-hand container is not present at the time of the page load, but in fact obfuscated and then later re-assembled via javascript and inserted into the DOM.

that means that by the time RTA runs to register custom actions on the links on a website, it won't find any because there aren't any yet. i can't really think of any good solution to this problem as the website itself is making it a bit hard for RTA to work.

a solution would be to run the link registration a second after the DOM has loaded, but that would break link catching for those who are faster at clicking; some pages may load for several seconds before the RTA script gets triggered. it would also not help for rendering scripts such as the one on extratorrents that take longer than a second to display the content, for whatever reason.

another option is to periodically re-run link detection, but that partially runs into the same issues as the previous solution, and may also decrease website performance.

what this essentially means it that i don't have a good solution for this issue. i'm open to suggestions.

**Comment by tomballgithub** [comment]
Make a configuration box to delay the start of link catching?  I for
example would just use it on all sites.

Or make a method to manually force a rescan.

On Mar 1, 2017 6:47 AM, "Julian" <notifications@github.com> wrote:

this is a problem with that particular site. if you check the source code
(ctrl+u) you'll see that the code for the right-hand container is not
present at the time of the page load, but in fact obfuscated and then later
re-assembled via javascript and inserted into the DOM.

that means that by the time RTA runs to register custom actions on the
links on a website, it won't find any because there aren't any yet. i can't
really think of any good solution to this problem as the website itself is
making it a bit hard for RTA to work.

a solution would be to run the link registration a second after the DOM has
loaded, but that would break link catching for those who are faster at
clicking; some pages may load for several seconds before the RTA script
gets triggered. it would also not help for rendering scripts such as the
one on extratorrents that take longer than a second to display the content,
for whatever reason.

another option is to periodically re-run link detection, but that partially
runs into the same issues as the previous solution, and may also decrease
website performance.

what this essentially means it that i don't have a good solution for this
issue. i'm open to suggestions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bogenpirat/remote-torrent-adder/issues/193#issuecomment-283330993>,
or mute the thread

**Comment by bogenpirat** [comment]
a possibility would be to add a small menu to the RTA button that contains a button that triggers a re-scan of the page. but in terms of usability, that's not so far removed from just doing the right click -> RTA flow. do you think this would be an improvement nonetheless?

i'm not entirely sold on the other idea.

**Comment by tomballgithub** [comment]
Well, at least for pages with many links it would avoid the need for
multiple right clicks.  Could just do it once.  Would really prefer an
automated way to have the delayed scan selectable.

Is it possible to have a regex to delay only on certain pages?

On Mar 1, 2017 8:15 AM, "Julian" <notifications@github.com> wrote:

a possibility would be to add a small menu to the RTA button that contains
a button that triggers a re-scan of the page. but in terms of usability,
that's not so far removed from just doing the right click -> RTA flow. do
you think this would be an improvement nonetheless?

i'm not entirely sold on the other idea.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bogenpirat/remote-torrent-adder/issues/193#issuecomment-283350911>,
or mute the thread

**Comment by tomballgithub** [comment]
It works!

**Comment by tomballgithub** [comment]
I tried 2000, 1000, and 500 and they all work.  Thank You

**Comment by bogenpirat** [comment]
sweet, thanks. i'll push a release in a bit.
