### ISSUE TITLE
Failure Error Code 500, Deluge 1.3.14

### ISSUE THREAD

**Issue by sethjk** [bogenpirat/remote-torrent-adder#195]
Recently updated to Deluge 1.3.14 and now RTA isn't adding torrents.  All server info is correct but am  "server responded with irregular HTTP Error Code 500"

Tried it on Mac and Windows 7.

**Comment by bogenpirat** [comment]
yep, seems like they're finally throwing errors if the content type for a request isn't correct (cf. deluge-torrent/deluge@11e8957deaf0c76fdfbac62d99c8b6c61cfdddf9).

i've fixed this in d989e9d. should be backward-compatible since the request specification was the same in previous versions. a fix will be out within the hour.

**Comment by sethjk** [comment]
Thx. works great now!
