### ISSUE TITLE
Yatp and Quasar support

### ISSUE THREAD

**Issue by wepae46** [bogenpirat/remote-torrent-adder#196]
Could Yatp and Quasar support be added?

Much appreciated

**Comment by bogenpirat** [comment]
quasar looks pretty sleek, but does it have a webui? couldn't find any info about that.

yatp is a bit problematic because its api seems to only accept URIs (http://someurl, file://c:/xyz.torrent) whereas RTA will only ever send actual torrent files (unless it's a magnet link); thus dealing with authentication schemes so torrent clients don't need to (which they usually can't anyway).

in either case i'm certainly interested but i'll have to look at whether it's even feasible in more detail.

**Comment by wepae46** [comment]
Yes, Quasar has an webui (65251/web)

**Comment by bogenpirat** [comment]
quasar also only allows URLs to be added, there are no file uploads just like in yatp.

that's a shame, because these are interesting addons... then again, at least quasar allows you to "add" (to the library?) as well as "stream" (meaning play straight away) files. and that's the point where i'm not sure that RTA is the right tool for the job. using some dedicated chrome extension for this purpose that supports both of these actions would make more sense.
