### ISSUE TITLE
Remote torrent adder doesn't work anymore

### ISSUE THREAD

**Issue by Marbellasaad** [bogenpirat/remote-torrent-adder#197]
Hello.

Remote Torrent Adder worked a week ago but atm nothing. When i had torrent i have no error code,nothing changed in my setup.

My friend have the same problem. So i tested on Firefox with this addons : https://addons.mozilla.org/en-US/firefox/addon/bittorrent-webui-120685/ and it work. Transdroid work too on android.

I use ruTorrent,i even have reinstalled it completly and tested on a fresh installation. I tested an other chrome extension nammed Xirvik and it doesn't work too,it just gave me an error "timeout".

**Comment by bogenpirat** [comment]
i've not changed anything in the rutorrent-relevant code in over 2 weeks.

please take a look at the developer console (F12) of this page: https://www.ubuntu.com/download/alternative-downloads as well as the script's background page (`chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci` -> enable developer mode -> views: background page). any errors in either of them? please paste me a screenshot.

if it's urgent, try removing the extension and re-adding it, re-doing your settings.

**Comment by Marbellasaad** [comment]
Hi,firstly thanks for the (quick)replie.
I've already removed my extension two times & reinstalled it.

When i'm the Ubuntu page the console doesn't print anything : https://puu.sh/uPAD3/46e9e60e22.png

Nothing too when i see the background page : https://puu.sh/uPAIo/8d5cd8a464.png

Thanks !

**Comment by northfacts** [comment]
same issue for me, i did not change anything on my rutorrent config, no update... nothing and he doesn't work anymore

**Comment by rafale30** [comment]
Hi bogenpirat,

Same problem for me. I've tested on various website, trying to update my chrome (56 ->57) : always the same problem. The plugin switch to green correctly, it detect correclty the torrrent in the webpage.
When i click on the link to download the .torrent: no reactions of the plugin.

Do you have an idea ?

**Comment by bogenpirat** [comment]
@Marbellasaad okay thanks, that looks good.

seeing as my test setup works fine: do you guys happen to use a seedbox provider, or do you run your own setup for rutorrent?

in either case: which version of rutorrent are you running?

**Comment by rafale30** [comment]
For me : rtorrent 0.9.6/0.13.6
I use my own dedicated server.

**Comment by bogenpirat** [comment]
@rafale30 okay, that's the rtorrent/libtorrent versions. what about ruTorrent? if you cloned their repository via git, do `git log --tags` and see the topmost commit's commit message that'll say something like "mark version 3.6".

**Comment by rafale30** [comment]
It's the same problem with the right click.

For the rtorrent, i've used a package to install it, what is exactely you action you want ?

**Comment by bogenpirat** [comment]
*RU*torrent. the web ui that doesn't come with rtorrent.

**Comment by Marbellasaad** [comment]
I run it via an dedicated server too. I used bytesized connect so it's updated (https://github.com/bytesizedhosting/docker-bytesized-rutorrent)

**Comment by rafale30** [comment]
I've checked, and y have many commit like: 

Author: novik65 <Novik@users.noreply.github.com>
Date:   Wed Oct 16 11:35:37 2013 +0000

    mark version 3.6

**Comment by bogenpirat** [comment]
alright, i updated my chrome and rutorrent (i run a 3.6-based commit and the same version as @rafale30 for rtorrent/libtorrent), adding still works fine for me. so that's where i run out of ideas and have to take wild guesses.

@rafale30 can you replicate what @Marbellasaad got after following [these](https://github.com/bogenpirat/remote-torrent-adder/issues/197#issuecomment-287568644) instructions?

@all having the developer tools open, select the network tab and try adding another torrent. then leave it open for a while. does its state ever change from pending (like in @Marbellasaad's screenshots)? if so, can you show me a screenshot if there's an error in it?

if that's unfruitful, what might help in cutting the trial and error phase short: either of you willing to lend me a login to their box to try and replicate the issue?

**Comment by rafale30** [comment]
I've test, the same result that Marbellasaad, no more information in the developer view (i am on windows/chrome 57)

**Comment by bogenpirat** [comment]
do any of the headers look wrong/weird when you click on the request (careful they might contain your base64-encoded password)?

**Comment by rafale30** [comment]
For me, no complicated password.
bogenpirat, do you have an email adress to send to you my config and an user/password to test on my env ?

**Comment by Marbellasaad** [comment]
Yeah i can give you my axx,how do i pm you on Github ?

**Comment by bogenpirat** [comment]
i don't think that you can. please send me an email at juliii@gmail.com, thanks.

i'll need to add a small torrent for testing purposes; i usually use one of these: http://www.osst.co.uk/Download/DamnSmallLinux/

**Comment by Marbellasaad** [comment]
I sended you an email

**Comment by bogenpirat** [comment]
thanks to @Marbellasaad i can see that the rutorrent setup doesn't appear to be the problem since i could add torrents just fine from my chrome installation.

just to make sure: you guys have the most current version of RTA from the web store; 1.2.11, yes?

@Marbellasaad, could you send me your configuration of the extension via mail? you can export it like so: https://github.com/bogenpirat/remote-torrent-adder/wiki/Backup-&-Restore-settings

if there's any sensitive data in that string, feel free to censor it with XXXes.

**Comment by Marbellasaad** [comment]
I sended you my settings,yeah i have the last version from web store.

**Comment by rafale30** [comment]
Same.

Julian, i have send to you an account to have another env to test.

**Comment by bogenpirat** [comment]
thank to you both.

since i can add things just fine, i went back to look at @Marbellasaad's screenshot and realized that the pending request might be a download, not the POST request to the webui.

dumb question: can you guys simply download a torrent file? to try, briefly disable RTA in your extension settings (`chrome://extensions`) and click on a .torrent link.

**Comment by Marbellasaad** [comment]
yeah i can

**Comment by bogenpirat** [comment]
alright, so we have:

1. i can do everything fine with each of your setups, including with @Marbellasaad's settings
2. manually downloading torrent files works fine
3. as per the last screenshot [here](https://github.com/bogenpirat/remote-torrent-adder/issues/197#issuecomment-287596182), it might be that [the extension](https://github.com/bogenpirat/remote-torrent-adder/blob/master/miscapis/functions.js#L52) actually fails to download the .torrent file.
4. i can't reproduce this issue on my end with identical extension settings

two further questions:

- can i get you guys' exact chrome version numbers? it's under `chrome://help/`.
- do you guys happen to use any possibly intrusive extensions that might be blocking requests? if so, could you check whether RTA performs as expected if you briefly turn them off, reload the tab containing the .torrent link and then clicking on a torrent?

**Comment by rafale30** [comment]
Chrome Version 57.0.2987.110

I have deactivate all my extensions, same problem :-(

When i deactivate RTA, the .torrant is doanloader by my downloader or the chrome downloader.

**Comment by bogenpirat** [comment]
alright, that sucks, because i really can't think of any reason why this would happen. i'm running the same version of chrome btw.

another approach for the same issue: if you enable RTA for the incognito mode, then open an incognito window (ctrl+shift+n) and try adding a torrent, does it work then?

**Comment by rafale30** [comment]
Yes, i have already try ...  : -(

**Comment by bogenpirat** [comment]
wait, it does work then?

**Comment by rafale30** [comment]
No, same problem on the private mode

**Comment by rafale30** [comment]
I've do various test : Uninstall // Change with second PC // reconf // test on other website // test with magnet : always the same result :-(. It's very strange.

**Comment by bogenpirat** [comment]
unfortunately i can't think of what this could be other than outside influence (other extensions, your isp blocks .torrent files, etc)

@rafale30 do you have the same situation in the developer tools as @Marbellasaad had in [his last screenshot here](https://github.com/bogenpirat/remote-torrent-adder/issues/197#issuecomment-287596182)? meaning: there's a request from functions.js:74 that just stays as "pending"?

a last way of approaching this would be that i connect to one of your (client) computers via teamviewer and check out the developer console myself... but i wouldn't be a fan of having that done to me, so i'd understand if neither of you is up for that.

**Comment by rafale30** [comment]
No pb for me. Look your mail.

**Comment by rafale30** [comment]
Wait !! I have found a way ! When you activate the extension, if you click on the link in this page : https://www.ubuntu.com/download/alternative-downloads     -> it works !

BUT, if try to download an another link, the extension seems broken, an no link is downloaded, and the ubuntu download is KO.

I send to you by mail one exemple.

**Comment by rafale30** [comment]
To all, do you use the tracker t4*11.li ?

**Comment by Marbellasaad** [comment]
yeah,but i use nyaa/others

**Comment by rafale30** [comment]
Try this:
 - close all windows of chrome
 - open chrome and go to the extension manager, deactivate and reactivate RTA
 - try to download a torrent, but NOT on T411

Probably Success !

I exchange with bogenpirat to find a solution. The problem, when you try to download with t411, RTA "stuck", and all test to download on another website is impossible. Only solution, reload the extension.

**Comment by bogenpirat** [comment]
okay @rafale30 was very kind to allow me to check a few things and it turns out that his particular problem was indeed just with this t411 website. it has to do with the fact that, interactively, chrome will display a warning about downloading files from the site, because the domain is flagged as malicious by google. this warning dialog prevents RTA entirely from downloading the torrent file.

we tested this by trying to download the torrent file manually by clicking on the download link while having CTRL pushed down; this opens a new window that displays a chrome-based warning.

@Marbellasaad can you check whether the same is the case for you?

if so, there's not much that i can do about this. the best bet for t411 is, as @rafale30 said, to wait until google de-lists the domain as a malicious website.

**Comment by Marbellasaad** [comment]
Yeah it work,thanks your for the help 👍

**Comment by rafale30** [comment]
Just for information, good news, T411 will be moved to https://www.t411.ai from 24 march.

So ... the problem with RTA will be solved with moving :)
