### ISSUE TITLE
Support dropped for embedded credentials in subresource requests (Chrome 59)

### ISSUE THREAD

**Issue by techietrash** [bogenpirat/remote-torrent-adder#198]
Looks like https://username:password@server type links are being blocked starting with Chrome 59.

https://www.chromestatus.com/feature/5669008342777856

> We should block requests for subresources that contain embedded credentials (e.g. "http://ima_user:hunter2@example.com/yay.tiff"). Such resources would be handled as network errors.

I get this error:
"**Server responded with an irregular HTTP error code:
0:**" when adding torrents (to rutorrent) with remote torrent adder.

![failure-0](https://cloud.githubusercontent.com/assets/8942018/24478041/5f1083b8-14a7-11e7-93bb-21f77af607a0.png)

Tracked down this error in the console of the background page for Remote Torrent Adder today, using Chrome Canary (Version 59.0.3054.0) on Mac

```functions.js:9 [Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.
XMLHttpRequest.sendAsBinary	@	functions.js:9```

**Comment by techietrash** [comment]
More reading:
https://bugs.chromium.org/p/chromium/issues/detail?id=435547

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/lx-U_JR2BF0

I wonder if we can use cookie for rutorrent (and others) instead?

**Comment by bogenpirat** [comment]
i've seen this notice before and figured it was buggy since we don't use url-inline credentials in either the [webui-specific code](https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/ruTorrentWebUI.js#L7) nor our [helper method](https://github.com/bogenpirat/remote-torrent-adder/blob/master/miscapis/functions.js#L3).

unless by "embedded credentials" they're referring to the [XHR specification](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open) where you can supply a username/password as parameters to the `open()` call.

... which would be pretty detrimental to the extension, as it would cripple at least 90% of client support. and good luck getting all those clients to change their authentication scheme; that absolutely won't happen.

a workaround at least for basic auth would be to manually set the authorization header. but that'll lead to complications with configurations that use http digest, which is a bit more complicated to implement. either way, it seems a bit dumb to have to re-implement http authorization when the browser can/should handle it, according to standards.

i've confirmed that the issue exists with canary. thanks for the links, but i'm not seeing anything useful wrt fixes for this issue. i'll monitor

**Comment by techietrash** [comment]
Thanks for the response.

Hopefully this change doesn't make it's way to Chrome Stable, but we shall see. It would be a major bummer because I love the ease of this Extension, it's great!

Please keep us updated if you find a workaround, cheers!

**Comment by bogenpirat** [comment]
well, the workaround would work ok [which i've tested]. it'd just convolute the code a lot, which sucks.

**Comment by bogenpirat** [comment]
promised @doezer over in #200 a test build. please have a look whether this works for you guys in ruTorrent. instructions are in https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code, zip is here: [remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/910150/remote-torrent-adder.git.zip)

**Comment by Doezer** [comment]
I'll test that in the evening, thank you.

**Comment by techietrash** [comment]
Seems to work well for me on the latest chrome canary, thanks 👍

**Comment by dregge8** [comment]
Working great for me in Canary! Seems fixed!

**Comment by Doezer** [comment]
I get this error:
https://i.imgur.com/KLOM6uz.png
Uncaught TypeError: Cannot read property 'sendRequest' of undefined
https://i.imgur.com/ZF8XtB3.png
Here's the seedbox side logs: [11.04.2017 08:58:55] Bad response from server: (401 [error,gethistory]) <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>401 Unauthorized</title> </head><body> <h1>Unauthorized</h1> <p>This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.</p> </body></html>
Also, consequently of using the fix, it invalidates my current authentication from rutorrent.

**Comment by bogenpirat** [comment]
can you check the following for me: go to rutorrent and log in normally, then hit f12 and go to the network tab and select one of the requests to the left, then check under response header on the right: is there one that's called `WWW-Authenticate` and starts with `Digest ...`?

**Comment by Doezer** [comment]
Yes there is.

**Comment by pbrink231** [comment]
I think this is related to my issue #141 (can close that one because it is different than the old issue)

Here is the developer spit out when i get this error.

Here is what i get when i receive the error

image

Hopefully this helps. Looks like it is net::ERR_SPDY_PROTOCOL_ERROR

This is the place it brings me to

XMLHttpRequest.prototype.sendAsBinary = function(datastr) {
function byteValue(x) {
return x.charCodeAt(0) & 0xff;
}
var ords = Array.prototype.map.call(datastr, byteValue);
var ui8a = new Uint8Array(ords);
this.send(ui8a.buffer); <--- This is the line that fails
}

**Comment by pnoeric** [comment]
FWIW I'm on Mac Chrome, Version 58.0.3029.96 (64-bit)

I'm having the same problem with HTTP error code 0. Can't add any torrents. It's trying to talk to my ruTorrent at my seedbox.

Happy to provide more info/debugging details, whatever is needed :-)

**Comment by pnoeric** [comment]
**FWIW for anyone else new who is getting the HTTP 0 error-**- I was also having this problem, and thought it might be related to this, but I ended up turning on the background page and doing some debugging and realized that the "host" field should not have https:// at the beginning.

One small suggestion, maybe we could add an example to the label for the "Host" field, like "this should be only 'server.com' or the IP address, not 'http://' in front."

Anyhow-- amazing plugin and works well for me right now. Thanks ;-)

**Comment by Doezer** [comment]
Hello, I stopped using the plugin but I reactivated it (the one you provided in unpacked form) and it's still not working. Now I have a 404 error. The plugin seems to be adding the port number although there is none
XXXX.com/rutorrent/:/upload.cgi

**Comment by Doezer** [comment]
I think this issue can be closed now.

**Comment by GiowGiow** [comment]
Bump
