### ISSUE TITLE
Label/Directory interactivity popup always on

### ISSUE THREAD

**Issue by Neoakb** [bogenpirat/remote-torrent-adder#208]
I can't seem to disable the Label/Directory
interactivity popup

**Comment by Neoakb** [comment]
Chrome Version 58.0.3029.110 (64-bit)

I've restarted both Chrome and my PC to no avail.

**Comment by abqnm** [comment]
Same here after updating qBittorrent to 3.3.13 which fixed some security issues in the WebUI.  Maybe this has broken the extension?

**Comment by dooley74** [comment]
Joined just to say "Me too" same error as above. Win7 using Chrome browser

**Comment by abqnm** [comment]
To OP and @dooley74, it may be relevant to share your torrent client as well. Are either of you using qBittorrent version 3.3.13? I updated my client yesterday, but it also seems the extension was updated yesterday as well, so I'm just trying to help see if the issue is client related or due to a change in the extension.

**Comment by dooley74** [comment]
The "me too" was in relation to ops initial post. Same OS, same version of qBittorrent, and same problem.

**Comment by dooley74** [comment]
Just removed remote torrent adder and reinstalled with latest version, still getting same error.

**Comment by abqnm** [comment]
@dooley74  Thanks. I asked because I wasn't sure if your "me too" was in response to my detailed reply, or the original post by @Neoakb which didn't list anything beyond their Chrome version number with no mention of client or OS. 

So depending on what client @Neoakb is using, it may clarify if it's just due to the changes in the WEBUI for qBT 3.3.13, or changes to the extension.

**Comment by dooley74** [comment]
reverted back to version 3.3.12 and issue is no longer there

**Comment by abqnm** [comment]
Thanks for updating, @dooley74.  That at least confirms that it was the CSRF vulnerability change to qBT 3.3.13 that did it.  I am by no means proficient in java, but the code for this extension doesn't appear to provide the referrer in the header, so this is likely why it is failing with 401:Unauthorized.

**Comment by landmines** [comment]
I'm having the same problem.  WIndows 10, Qbittorrent.  I just joined to post this comment, I don't know crap about programming.  Any options to try to get it working?

**Comment by landmines** [comment]
Oh, i'm not sure if everyone else is having the same problem, but it won't let me add torrents now either.

**Comment by abqnm** [comment]
@landmines Yes, that is the issue.  It gives the popup every time, but also refuses to add the torrent regardless.  OP wasn't exactly clear with that information.  In the meantime, you can revert to [qBittorrent 3.3.12](https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-3.3.12/) which does not have the security hole patched yet, but does still work with the extension.  You can simply install 3.3.12 overtop of your 3.3.13 install and it will retain your settings.  I know this isn't ideal, but it will work until it can be corrected in the extension.

It's only been a day since the issue was opened, so I assume @bogenpirat will get to it in due time.

**Comment by landmines** [comment]
Thank you for the reply.  I'll revert until there is a patch then.

**Comment by bogenpirat** [comment]
yep, i kinda mighta done only minimal testing for this one, my bad. apologies.

@Neoakb the label/directory dialog is indeed always present. this is a bug and i've fixed it in 9800f5b. i'll hold off on publishing a new version with this fix while i try to remedy the 3.3.13+ situation.

@abqnm this is indeed a problem, but independent from the issue here. my test setup with qbittorrent 3.3.7 works fine. i'll close this and would ask that you direct your attention to #210 for this new problem. thanks for the good ground work so far.

**Comment by abqnm** [comment]
@bogenpirat yeah I realized a bit later that it probably wasn't the same issue as OP, but I didn't want to create a new issue until you had a chance to see it. Thanks for fixing this bug as well as working on the CSRF fix update.
