### ISSUE TITLE
Qnap download station no longer working

### ISSUE THREAD

**Issue by 666Warlock666** [bogenpirat/remote-torrent-adder#227]
no longer working with qnap download station 5.0.69

**Comment by bogenpirat** [comment]
unfortunately i don't have access to a qnap download station, so i can't figure out what has changed.

if you can send me a dump of you uploading a torrent file(/magnet?), i could try and see if i can fix it or have to add another implementation.

**Comment by EzerchE** [comment]
Hi, I want to help about fixing that. Can you tell me where can i find the dump file?

**Comment by bogenpirat** [comment]
well, the idea is that you have to capture(presumably) two actions when using your regular web interface so that these actions can be duplicated in code on RTA's end:

1. login procedure
2. adding a torrent

for that purpose, you'd want to open a tab, hit `f12` to open the devtools, switch to the network tab, enable `preserve log` and then log into your web ui. this action will be mirrored in one line (or many) in the devtools - typically it's a `POST` request, its request name may include something like "login" or "auth" - you'll have to go through the list and figure that out.

if you click on it, you get a list of http headers along with the payload's structure. most of that data is necessary to craft a request that RTA might use for sending automated login requests. after identifying the correct request, ideally, you'd just right-click it and `save all as HAR with content`. but that will contain both the torrent data and your webui's login/password credentials, which you might not want to share. in that case, a screenshot with some private headers (e.g. `Authenticate`) redacted are a good starting point.

once you're done with that, you repeat all of the above, but this time as you add a torrent file to your webui (ideally once via file upload and a second time via link, if the webui/torrent client supports magnet links).

let me know if you'd be into that and i'll reopen this
