### ISSUE TITLE
Notification not working on Chrome Version 68.0.3440.106 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by IscreaMan** [bogenpirat/remote-torrent-adder#243]
Notification (popup) not working on Chrome Version 68.0.3440.106 (Official Build) (64-bit). Neither when adding torrent nor through "hit me" button.

**Comment by Potplanty** [comment]
Have also been having this issue for a few months. Icon is greyed in Chrome taskbar, torrents still add fine but no popup/toast notification. Have completely removed and reinstalled RTA.

Chrome version 69.0.3497.100 (Official Build) (64-bit) running on Windows 10 Pro x64.

**Comment by aderusha** [comment]
Also experiencing this behavior,

Chrome: 70.0.3538.67 (Official Build) (64-bit) (cohort: 70_67_Win)
Remote Torrent Adder: 1.2.15

**Comment by campones** [comment]
same here

**Comment by MDS0LDI3R** [comment]
I am not having the grayed out issue but I am not getting notifications.

Chrome: 70.0.3538.110 (Official Build) (64-bit)
Remote Torrent Adder: 1.2.15

Don't know when it started, the main site I use doesn't work with Remote Torrent Adder so it's kind of a convenience I infrequently use. I only noticed because I changed seedboxes today and was trying to test it.

**Comment by Selas81** [comment]
Same issue here, hoping for a fix.

**Comment by campones** [comment]
i don't think this is an issue with remote torrent adder, same happen with others extension as gmail checker etc.  need to restart to have it poping again, weird!

**Comment by Selas81** [comment]
> i don't think this is an issue with remote torrent adder, same happen with others extension as gmail checker etc. need to restart to have it poping again, weird!

restart? I can't get it popping at all on RTA that is..

**Comment by campones** [comment]
oh I see, my bad then.

**Comment by HeroesKiller** [comment]
Unfortunately, I have the same problem.
Chrome v79.0.3945.117, 64bit

**Comment by Selas81** [comment]
I got it fixed for me a few months ago, but had forgotten all about this thread sorry.

As I remember this issue comes from Chrome using the Windows native notifications, rather than built in notifications, so the easiest fix is to simply enable Windows notifications again.

However if you don't want that noise, do like me, and disable native notifications with this link:
chrome://flags/#enable-native-notifications
If that doesn't help, let me know please, and I will tinker with it some more.

Step by step tutorial:
https://www.wikihow.com/Enable-or-Disable-Native-Notifications-for-Google-Chrome
Video:
https://youtu.be/cFM0CStbjTU

**Comment by Selas81** [comment]
BTW native notifications is kind of a new feature in Chrome, I believe it was enabled around a year ago.

**Comment by HeroesKiller** [comment]
Hello.

Thank you, it works like a charm now. :-)

Regards,
HK

čt 9. 1. 2020 v 20:50 odesílatel Selas81 <notifications@github.com> napsal:

**Comment by ihatemyisp** [comment]
The fix doesn't work for MacOS and Chrome 80.0.3987.66 (Official Build) beta (64-bit).

The test notification works, but torrent adds never fire one off.

**Comment by bogenpirat** [comment]
alright, this was one i'd actually experienced myself, but chalked up to the OS's attempt at not littering me with notifications. guess that was an overestimation. seems to work fine for me in 77ed9473bd98bcf06c904703af8babf3dadb2369.

please let me know if this is still an issue and i will re-open.
