### ISSUE TITLE
Add Support for qBitTorrent 4.2.0

### ISSUE THREAD

**Issue by gbonk** [bogenpirat/remote-torrent-adder#253]
I started running the next Alpha of qBitTorrent v4.2.0 alpha.  Worked fine with 4.1.5 . 

Not sure what the issue is, but I'll see if I can get an error message. Yes I turned off the CRSF protection as I had to for 4.1.5

**Comment by gbonk** [comment]
Did some digging,  according to the qBitTorrent Docs, they now require the full API path.

So, /login should now be /api/v2/auth/login

**Comment by bogenpirat** [comment]
using this thread to talk about api v2 (qbt v4.1.0 and above) support.

thanks to @gbonk who made the initial PR above, v2 support is here. since i'd like to keep the api v1 code (qbt 4.1.4(5?) and below), i've put the code under a new server name in the configuration dialog. that means that current configs need to be re-written for new server entries.

alternatively, if you go to `chrome://extensions` and in RTA's field click on inspect views: background page, you can use the console tab to run the following command to duplicate/convert all current qBt v1 server configs to qBt v2 configs:
```js
var oldServers = JSON.parse(localStorage.getItem("servers"));
for(var i = 0; i < oldServers.length; i++) {
  var server = oldServers[i];
  if(server["client"] == "qBittorrent WebUI") {
    var newServer = Object.assign({}, server);

    newServer["client"] = "qBittorrent v4.1+ WebUI";
    newServer["name"] += " v2";
    newServer["qbittorrentv2dirlabelask"] = newServer["qbittorrentdirlabelask"];

    oldServers.push(newServer);

    localStorage.setItem("servers", JSON.stringify(oldServers));
  }
}
```
you can then refresh RTA's config and the new server should be there.

a testable package is here: [zip](https://github.com/bogenpirat/remote-torrent-adder/archive/c7b2e31f3265411a563426fc51a3e83a34aa769c.zip)
use these instructions to try them out: [Try-new-code](https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code)

please report back and let me know whether there are any issues.

**Comment by BCITMike** [comment]
I've been using that package for at least a month with no known issues. When will this be merged in and released to the chrome store?

My computer rebooted today unexpectedly and the developer version was no longer installed and lost the configured ones I had.  My guess is that I unzipped it to my ramdisk and so it was missing next time Chrome launched, *shrug*

But I was hoping this would just get merged in and released since it worked so well during my testing.

Thanks!

**Comment by bogenpirat** [comment]
> But I was hoping this would just get merged in and released since it worked so well during my testing.

the faster i get (more) feedback, the more confident i feel releasing it. i hadn't gotten any before this, so thank you.

can't give you a definite timeframe when i'll release this code, i'm hoping to add some more functionality and fixes to the next release.

**Comment by seanbperiod** [comment]
4.2 stable is out today - glad to see this is being worked on again - holding off on updating qb until this is updated. Thanks!

**Comment by bmtphoenix** [comment]
I just updated to 4.2.0 because 4.1.x suddenly stopped working with RTA. Updating did not fix it.

**Comment by tinganhsu** [comment]
Using testing code, work perfectly with 4.2.0 qBittorent! Thanks man!

**Comment by victordk** [comment]
Test code worked fine here :)

**Comment by TTLucian** [comment]
Test package works fine.

**Comment by Dulanic** [comment]
Test package fails here. If I try to access my qbittorrent via webui, I am unable to (404), if I disable, it works again.

**Comment by BCITMike** [comment]
> Test package fails here. If I try to access my qbittorrent via webui, I am unable to, if I disable, it works again.
> 
> HTTP ERROR 401

You're going to need to provide more details. This is a chrome add-on, it has zero interference with accessing qbittorrent's webUI. (Your problem is something else).

**Comment by Dulanic** [comment]
You can say that, but if I disable the addon, it works, I enable, it doesn't. I have tried it 6 times now. I am not sure what other details to provide since it is a 401 error there isnt anything really to show.

**Comment by BCITMike** [comment]
Do you get prompted to enter your QB credentials again? 401 is authentication problem.

Does the webGUI work from a non-chrome browser? 

How are you configuring the server in the adder?

In QB, did you turn off the CRSF protection?

**Comment by Dulanic** [comment]
1: No, it doesn't do anything just straight 401 when addon enabled.
2, Yes, including in Edgium.
3. 
![image](https://user-images.githubusercontent.com/2948206/70803613-13957900-1d7a-11ea-8fb9-d8ccd81b1187.png)
4. Yes

**Comment by victordk** [comment]
Dulanic that is not the test code - thats the standard extenstion. It should say qBittorrent v.4.1+ Webui in the Type Host field. If you run the the test code - delete your entry and enter it again.

**Comment by Dulanic** [comment]
I've tried it with both, so that seems that it is not the test code thats my problem, its the overall extension.

![image](https://user-images.githubusercontent.com/2948206/70808599-a12a9600-1d85-11ea-8ae3-e468b17de228.png)

**Comment by BCITMike** [comment]
I am able to run both standard and test extensions. Just configure this server in the test version options making sure to select the 4.2.x QB option and delete from standard options. 

I don't recall if the test has two QB options, one for 4.1.x and one for 4.2.x...

**Comment by hyenaHD** [comment]
Dear Developer,

The test package works well with my qbittorrent 4.1.8 server, please advise me when could i expect for the official final release!

Greetings and thanks for your hard work!

**Comment by gbonk** [comment]
Worked great for me.  Took me a while to understand that I needed the Code Snippet from above AND the source zip.

**Comment by Litcube** [comment]
Got the test package to work.  What else are we waiting on for standard release?

**Comment by bogenpirat** [comment]
for me to find some time. ;-)

**Comment by TTLucian** [comment]
Test code has been working with no issues. Any news on new version release? "Developer extensions" warning in Chrome is getting really annoying!

**Comment by feerlessleadr** [comment]
Test code is working for me on 4.2.1.

The only thing that isn't working (and I'm not sure if it is test code related or not) is that the option "Label/Directory interactivity".

I'm assuming this is supposed to allow for me to select a category for new torrents added, however I don't get a pop-up (or any other indication from the extension), and the torrent is added without a category. Not a huge deal, since I can manually assign one, but a minor pain regardless.

**Comment by nkoz18** [comment]
Test code is working for me on 4.2.1 to add torrents.

"Label/Directory interactivity". option doesn't prompt for category.

qBitTorrent / Windows 10 x64 / Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by rrrevin** [comment]
This also works for me. Upgraded to 4.2.1 qbittorrent-nox; joy in Mudville today.

**Comment by hyenaHD** [comment]
The test code worked well for me for a while but since the latest update of the qbittorrent/chrome it not works anymore.
chrome 79.0.3945.117 
qbittorrent 4.1.8.r02

**Comment by hyenaHD** [comment]
> The test code worked well for me for a while but since the latest update of the qbittorrent/chrome it not works anymore.
> chrome 79.0.3945.117
> qbittorrent 4.1.8.r02

I found a solution for this issue, after i switched of the Enable Cross-Site Request Forgery (CSRF) protection in the webui options the test code works again :) .
Looking forward for the final stable release.

**Comment by rrrevin** [comment]
> Looking forward for the final stable release.

Many of us are :)
Great work Julian!

**Comment by jasonhpchu** [comment]
Works for me on 4.2.1, commit the change to release!
btw, I had to also switch off those security options before it worked.

**Comment by BCITMike** [comment]
4 months for a new feature and no issues. Release the Kraken!

**Comment by Litcube** [comment]
Yes please!  The "developer mode" warnings on chrome are starting to give
me nightmares.

**Comment by andrelx** [comment]
Yes! Please release !

**Comment by TTLucian** [comment]
https://chrome.google.com/webstore/detail/torrent-clipper/cmhdhpcfabppigjedlenkmleklplflhp?hl=en

**Comment by hyenaHD** [comment]
> https://chrome.google.com/webstore/detail/torrent-clipper/cmhdhpcfabppigjedlenkmleklplflhp?hl=en

Unfortunately it not works with qbittorrent> 4.0.4

**Comment by TTLucian** [comment]
I have qbittorrent 4.2.1 x64 and it works perfectly! Check your setup!

**Comment by hyenaHD** [comment]
> I have qbittorrent 4.2.1 x64 and it works perfectly! Check your setup!

You have right , it was my misstake. 
Otherwise using the same 4.2.1 on my asustor nas.
Thanks for your information!

**Comment by virtualbitzz** [comment]
I tried manually patching via the console and switching over to the test code. My problem is that the software no longer detects when I click a magnet link. It doesn't respond at all. Looking at the console, it's not attempting to process a request. Using the old qbittorrent server type, it detects the magnet link, but I get 404 errors when using it, hence the workaround.

**Comment by alon24** [comment]
https://chrome.google.com/webstore/detail/torrent-clipper/cmhdhpcfabppigjedlenkmleklplflhp?hl=en
works if you clear the csrf check in qbitorrent

**Comment by rrrevin** [comment]
> https://chrome.google.com/webstore/detail/torrent-clipper/cmhdhpcfabppigjedlenkmleklplflhp?hl=en
> works if you clear the csrf check in qbitorrent

Thanks. I can confirm this works as well.
I'll switch back to Remote Torrent adder when Julian issues an official release.

**Comment by IShmelov** [comment]
Confirmed, works like a charm with qbt 4.1.9.1 and 4.2.1
Thanks for the fix!

**Comment by BCITMike** [comment]
@bogenpirat Have you abandoned this project? 5 months unreleased feature that is a MUST HAVE for QB 4.2.0 and the issues are filling up due to not having this released to the chrome store.

Just a reminder, since its another drop down option that doesn't effect existing working QB setups, there was NEVER a reason to hold back this update and taking months to release it is only causing more harm than good. I understand not wanting to push untested changes into the stable store, but this is irrelevant in this case.

Please release it to the chrome store already!  Thanks

**Comment by virtualbitzz** [comment]
> @bogenpirat Have you abandoned this project? 5 months unreleased feature that is a MUST HAVE for QB 4.2.0 and the issues are filling up due to not having this released to the chrome store.

I've abandoned RTA. I have family members who I need to support. Side loading plugins is not an option. 

I've moved on to Torrent Clipper, it works great

**Comment by tentaclemoose** [comment]
> I've moved on to Torrent Clipper, it works great

Thanks for the tip, I was looking for a replacement since this one seems abandoned and having chrome warn me about developer mode at every startup is annoying.

**Comment by RF-Nelson** [comment]
I can confirm that Torrent Clipper is a great drop-in replacement fort RTA.

**Comment by Ryrynz** [comment]
RIP RTA. What a shame @bogenpirat

**Comment by bogenpirat** [comment]
well, since this has sort of become the collecting tank for cranky qbt 4.2.0+ users (excuse the sarcasm over some of the dramatic posts here), a few words:

- code's been merged, some additional fixes were made (d791c14, 8fd58b22e0854c27bc1f3dbf501df937f5ebe0b0, eeee414e2669114dd1412f7a26562bb7b915c2c7)
- qbt versions based on the v2 api (4.1.4+ iirc) work
- you can keep CSRF protection enabled - the extension now (correctly) sets the Origin header
- recommending alternatives when this project seems abandoned seems fine, but don't post links. that's just blatant advertising
- sorry for the delay

**Comment by GithubMarcel** [comment]
uhm rta  v.3.2 works fine on qBittorrent v4.1.9.1 but if I install qBittorrent 4.2.5 (no settings changed) the popup shows a 404 error. any ideas?

**Comment by Terebi42** [comment]
This works for me now. NOTE: YOU HAVE TO RECREATE YOUR CONFIG using the new qbit 4.1+ option, your old setup will not magically start working.

**Comment by gerberanub** [comment]
> https://chrome.google.com/webstore/detail/torrent-clipper/cmhdhpcfabppigjedlenkmleklplflhp?hl=en
> works if you clear the csrf check in qbitorrent

how to clear csrf check ??  plz tell me in more detail...
