### ISSUE TITLE
Server didn't accept data: 200

### ISSUE THREAD

**Issue by ZataH** [bogenpirat/remote-torrent-adder#261]
I am getting this error now. I saw some of the other issue reports here regarding HTTP error:0, where it was mentioned to open inspec views. This is the error I see:
A cookie associated with a cross-site resource at http://host.domain.tld/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Using rutorrent btw

**Comment by bogenpirat** [comment]
that shouldn't be pertinent to us since ruTorrent authentication is done via HTTP Basic Authentication (headers) as opposed to anything with cookies. you've received this error because of the way your web server (or PHP? customized ruTorrent setup?) is set up; by default, cookies do not carry the SameSite attribute.

did the torrent actually add?
do you see this error message in the developer console (F12) of a regular ruTorrent browser session as well?
