### ISSUE TITLE
qbittorrent 4.2.0 x64 not work

### ISSUE THREAD

**Issue by timhuang1204** [bogenpirat/remote-torrent-adder#264]
as title
this do not support qbittorent 4.2.0 x64
it will show the error message below:
"Server responded with an irregular http error code 404"

but the webui is fine when i use chrome and type-in url

i have remove this extension and reinstall
but still got the same error

chrome ver: 78.0.3904.108
remote-torrent-adder ver: 1.2.15
win 10 pro x64 1909

**Comment by timhuang1204** [comment]
i am reinstall qbittorrent 4.1.9
and work fine

**Comment by Jynx2120** [comment]
> Server responded with an irregular http error code 404

I get this error as well, and the only version of qbit that this extension works with for me is 4.1.4. Looks like I'll be reverting yet again. This failure is very disappointing one, I expected the extension to work with this version of qbit. I'm sick of not being able to update qbit, very frustrating.

**Comment by seanbperiod** [comment]
there's already a thread for this: https://github.com/bogenpirat/remote-torrent-adder/issues/253

**Comment by Lordgoderic** [comment]
I'm also having this issue with 4.2

**Comment by Litcube** [comment]
Me too.  Can't seem to get it to work with the test package above, but maybe I'm doing something wrong.  Hoping for a new official version soon!

**Comment by Jynx2120** [comment]
Alright, so I got this working locally thanks to the suggestion from seanbperiod, thanks for the heads up. I downloaded the test stuff and installed from that threads direction. However, getting the extension to work with a domain name is a different story. I'm not sure why it doesn't work because nothing on my part has changed and it worked fine with the old extension. When I put my local IP in it works, when I put in my domain name in I get some 403 (forbidden) login error. The username and password for the qbit server are correct, port is forwarded, SSL checked, certs are good and I have the Label/Directory interactivity checked. Not sure what else to do. Am I doing something wrong?

**Comment by rrrevin** [comment]
Same issue here. Just upgraded from 4.1.9 to 4.2.1.

**Comment by bogenpirat** [comment]
let's revisit this if the problems persist in the next version. should be fixed though.

**Comment by Terebi42** [comment]
This works for me now. NOTE: YOU HAVE TO RECREATE YOUR CONFIG using the new qbit 4.1+ option, your old setup will not magically start working.
