### ISSUE TITLE
rutorrent 404 no input file specified

### ISSUE THREAD

**Issue by quadcom** [bogenpirat/remote-torrent-adder#270]
providers path to UI is /RPC2

SSL enabled, port 443 is set.

Always returns "404:No input file specified

![2020-03-13 16_02_12-Window](https://user-images.githubusercontent.com/7085931/76655747-62eb7100-6544-11ea-9761-528c6c614eb6.jpg)
."

**Comment by quadcom** [comment]
rtorrent v3.9

**Comment by meanddem** [comment]
This is the error I'm getting now as well. I hope there's a fix soon.

**Comment by bogenpirat** [comment]
just to confirm - when you punch `http://somedomain.com/RPC2/` into your address bar in the browser, you're greeted with the ruTorrent web ui?

if this **is not** the case: `RPC2` is a string you'll typically find in ruTorrent's configuration file assigned to the variable `$XMLRPCMountPoint` and it controls how the connection between ruTorrent and rTorrent works. this is irrelevant for the RTA configuration, since it just uses ruTorrent as an interface and never speaks directly to rTorrent (via the scgi or otherwise). you just have to give the extension the relative path to where you open your web interface in the browser, e.g. for `http://somedomain.com/stuff/ruTorrent/` the required string would be `/stuff/ruTorrent`.

if this **is** the case: does the address `http://somedomain.com/RPC2/php/addtorrent.php` exist, or does it give you a 404 not found error? if so, your provider(?) may have altered the ruTorrent software and changed paths.
