### ISSUE TITLE
catch jackett links

### ISSUE THREAD

**Issue by emilio215** [bogenpirat/remote-torrent-adder#271]
im struggling to get the regex working for jackett links.

an example looks like 

http://[MYIPADRESS]:[PORT]/dl/TRACKER/?jackett_apikey=[LONGSTATICSTRING]&file=The.Torrent.Name.S01.1080p.BluRay.DD5.1.x264

what ive tried

\?jackett_apikey=
\dl

any help would be appreciated

**Comment by JPRuskin** [comment]
I think you need to escape at least the questionmark in that regex - though it's not exactly the same, playing on [regexr.com](https://regexr.com) may help.

So, suggestion: "\?jackett_apikey=".

**Comment by emilio215** [comment]
just tried, no luck. thanks though ill check out that website.

**Comment by bogenpirat** [comment]
i just copy-pasted the suggestion from https://github.com/bogenpirat/remote-torrent-adder/issues/271#issuecomment-600841325 into my link catcher settings, tried it on [this](https://jsfiddle.net/be0kygjf/) sample link and RTA catches the link just fine (just doesn't add anything because the url doesn't exist, obviously). is the link format incomplete?
