### ISSUE TITLE
Failure - Server responded with irregular HTTP error code: 401: <!doctype html public "-

### ISSUE THREAD

**Issue by keodk** [bogenpirat/remote-torrent-adder#283]
Getting the above error after upgrading to v1.3.0 and 1.3.2. Had to revert manually to 1.2.15 before everything was working again.

Client i rtorrent with ruTorrent webUI

**Comment by keodk** [comment]
Getting the above error after upgrading to v1.3.0 and 1.3.2. Had to revert manually to 1.2.15 before everything was working again.

Client i rtorrent with ruTorrent webUI

**Comment by bogenpirat** [comment]
is your webserver using http digest auth? check this: https://github.com/bogenpirat/remote-torrent-adder/issues/281#issuecomment-670792953

**Comment by bogenpirat** [comment]
since i referred to that thread and gave the person over there a rejection, but recently revisited (and hopefully solved) the issue, please give https://github.com/bogenpirat/remote-torrent-adder/issues/281#issuecomment-673606027 a try and let me know over there if it works again.

i'm closing this issue for now, let me know whether you're experiencing an issue unrelated to digest after all and i'll reopen this.

**Comment by orobardet** [comment]
Hi,
Got the same issues too. Suddenly stopped working on a rtorrent/rutorrent with basic auth working for years.  
I just tried the test version proposed in #281, and it solves the issue!
