### ISSUE TITLE
Torrents not being added to ruTorrent again

### ISSUE THREAD

**Issue by GorillaJohnson** [bogenpirat/remote-torrent-adder#286]
hi, same issue as here https://github.com/bogenpirat/remote-torrent-adder/issues/278

Seem to be fixed but has started happening again 3 days agp.

Anyone else having the problem?

Thanks

**Comment by GorillaJohnson** [comment]
I'm signed into rutorrent and my seedbox no problem.

I'm a novice with this. are these the"devtools" you mention? 
developers.google.com/web/tools/chrome-devtools/open

if so i clicked network on the left and had 3 options "get started" "network issues guide" "Reference"

**Comment by bogenpirat** [comment]
sorry, i was referring to my earlier post:
> whether there are any error messages in the background page of RTA in the devtools (see chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci)
you enter the chrome://-url into your address bar and click on this link: 
![image](https://user-images.githubusercontent.com/1835496/90985687-e2627f00-e57d-11ea-85f6-10f7f18d66d2.png)
that should present you with a new pane or window in your browser that contains the "chrome devtools". when you have those open, follow the aforementioned instructions. that may help shed some light on what's going wrong.

**Comment by GorillaJohnson** [comment]
is this where i should be looking https://imgur.com/6tvkEMe

i went to chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci

Below that is https://imgur.com/a/WgdwoQp

When i click "Extension options" https://imgur.com/a/eBUXtDS

**Comment by bjmomo** [comment]
I am having this issue too, also with feralhosting. chrome, rutorrent.

under the addtorrent.php-->response headers in DevTools, there is this:
`WWW-Authenticate: Basic realm="[myusername]"`
under request headers there is no Authorization header

**Comment by bogenpirat** [comment]
@GorillaJohnson your first screenshot is the correct function of chrome (on the right side of the screen), however it is opened from the wrong place - the extensions overview screen of chrome instead of from within the context of the RTA extension. in order to see the link i screencapped in my last post, you may need to turn on the "developer mode" in the top right of the extensions overview screen. you can then view errors in the console tab that is visible on your first screenshot at the bottom of the right pane (dismiss "what's new").

your config doesn't have a port set. try setting one. do you use http or https? that would be 80 or 443, respectively.

@bjmomo you wouldn't happen to also have a missing port setting? if not, any errors under console?
in your case, it seems that a `WWW-Authenticate`-challenge wasn't answered. this might be the case when the request handler that deals with supplying credentials in the background didn't register to the correct URL.

**Comment by bjmomo** [comment]
thank you! adding port 80 fixed the issue. 👍

**Comment by GorillaJohnson** [comment]
same fix as above. big thanks
