### ISSUE TITLE
Downloads in a custom directory

### ISSUE THREAD

**Issue by dbombin** [bogenpirat/remote-torrent-adder#293]
Hi,

I am trying to download to a custom folder in a seedbox with rutorrent. By default the downloads go to /home20/user/downloads/PeliculasHD or
/home20/user/downloads/Series or
/home20/user/downloads/4K folders

But I want these downloads to go to /home20/user/downloads/Full

I have tried to put in directory field in RTA configuration the following: /home20/danb/downloads/Full but it doesn´t work, allways the downloads go to default directory.

I have created previously the folder called Full.

I upload some screeshots of my problem.
![20200926_205413](https://user-images.githubusercontent.com/71943028/94348248-e8df8d00-003a-11eb-9f7e-fbeb994dcc25.jpg)
![20200923_215510](https://user-images.githubusercontent.com/71943028/94348252-ed0baa80-003a-11eb-8971-3c113282494f.jpg)
![20200923_215448](https://user-images.githubusercontent.com/71943028/94348254-f0069b00-003a-11eb-8395-bab9384b617b.jpg)
![20200923_215410](https://user-images.githubusercontent.com/71943028/94348255-f0069b00-003a-11eb-84f4-beb5b4cf3b3f.jpg)
![20200923_215318](https://user-images.githubusercontent.com/71943028/94348257-f09f3180-003a-11eb-8a41-be73696d7825.jpg)

Thank you

**Comment by bogenpirat** [comment]
when you enable label/dir interactivity in the settings (as indicated in your first screenshot), the default directory setting from the configuration is overridden and instead the value selected in the interactivity dialog is used to add torrents.

if you specify a relative path (as opposed to an absolute one), RTA doesn't do any resolving. it just sends that setting to r(u)Torrent, so rTorrent will decide where to download to. in the case of a relative path, it'll take the standard downloads directory from its .rc file and append the given relative path.

if the above doesn't already help, check if rTorrent spits out any error messages when you try to add a torrent (if you have access to its log file). if you specify a path it cannot download to (e.g. because it is unwritable), it will automatically try to download to its default directory.

**Comment by dbombin** [comment]
Ok, thank you. I have included the Full/4K folder in dialog box when prompt in new box and works perfectly, Solved
