### ISSUE TITLE
Error ruTorrent but works ?

### ISSUE THREAD

**Issue by Nico83500** [bogenpirat/remote-torrent-adder#295]
Hi,
I'm using Edge Chromium 86 + Remote Torrent Adder + ruTorrent.
When I add a .torrent, I get a red error pop-up with the message : Could not contact ruTorrent - Error: Not Found
But I can see the torrent is added to ruTorrent so it seems to work.
Is it possible to fix it ?
Thank you !

**Comment by bogenpirat** [comment]
doesn't seem to be a problem with RTA - it works fine for me using the same edge, latest RTA and ruTorrent 3.10.

perhaps you're using a custom version of ruTorrent?

**Comment by Nico83500** [comment]
I'm using Swizzin installation script (rutorrent 3.10 is installed)

**Comment by bogenpirat** [comment]
i had a quick look at the swizzin bash scripts, but then instead decided to not bother reading that catastrophe further.

in any case, since the only problem is failure/success confirmation, and the error message stems from [here](https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/ruTorrentWebUI.js#L124), i'm guessing that the `addtorrent.php` script of your rutorrent installation behaves differently from the vanilla one.

the way of checking this out would be the following:
- go to `edge://extensions/`
- enable developer mode in the lower left, then click on the "details" link in RTA's entry on the right
- on the bottom, inspect the view of the background page. that should pop up a new window
- go to the network tab
- in some other tab, add a torrent to rutorrent using RTA. that should add a few entries similar to these: 
![image](https://user-images.githubusercontent.com/1835496/97486589-f058c580-195b-11eb-8b69-b1f2c4b2e20c.png)
- if you select the lower one and go to the preview tab on the right-hand side, the content looks like this for me:
```noty("1603913016684.torrent - "+theUILang.addTorrentSuccess,"success");```

i assume that this is not the case for you. care to share?

**Comment by Nico83500** [comment]
You're right, I don't have Success but Failed : 
![image](https://user-images.githubusercontent.com/6403141/97497180-6532fc00-196a-11eb-88dc-ea5065b512c4.png)
On the preview tab I get a 404 error.

**Comment by bogenpirat** [comment]
mind taking a look at the first request? under the headers tab, there should be a response header called `Location` that probably points to the latter url. is this the case?

**Comment by Nico83500** [comment]
Here is the Location from headers tab : 
![image](https://user-images.githubusercontent.com/6403141/97505090-7b47b900-1978-11eb-8a92-352fc6384a15.png)

**Comment by bogenpirat** [comment]
i'm just now noticing the `FailedFile` response parameter. you're saying the torrent adds properly? can you take a look at the rtorrent logs? does rutorrent say anything in the logs? it's possible that one of the additional plugins swizzin installs somehow tells rutorrent that the way RTA adds torrents isn't proper, then doesn't fail(??), but still redirects to a failure page. detecting failure to add for rutorrent unfortunately depends on http error codes (as is the case with this one), so it's difficult to just ignore this error in the code and have it display as successful.

i assume that your variant of rutorrent just has a different request scheme for adding torrents. if that is the case, you can look at the code in https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/ruTorrentWebUI.js and compare it to what sort of requests are made when you add a torrent manually via the web ui and then let me know what needs to be changed in the code. when we know that, i can check whether it makes sense to add that to the code.

**Comment by Nico83500** [comment]
Thank you, I'm trying to find where the logs are stored.

**Comment by Nico83500** [comment]
Perhaps I can give you an access to a Swizzin server if you want to look at it ?

**Comment by bogenpirat** [comment]
yeah, that'd work. if you want, shoot me an email to the address you get on the chrome webstore page with details.

**Comment by Nico83500** [comment]
No problem, done ;)

**Comment by bogenpirat** [comment]
thanks for the mail. i'm a bit confused.

what's causing the "error message" from RTA to be displayed is the fact that the server answers with a 404 response. is because the add request (which evidently works) redirects us to the same script name (`addtorrent.php`), however the path of that script is now lacking the path information (the `ruTorrent/php` folder). this is set in the addtorrent.php script here: https://github.com/Novik/ruTorrent/blob/master/php/addtorrent.php#L99 and my best guess is that this line is failing on your setup because `dirname($_SERVER['PHP_SELF'])` somehow returns an empty string (it is missing completely from the `Location` header that php outputs in the request). so that's a bug in either php, nginx, swizzin or the combination. a regular rutorrent installation on apache for example gives an http 200 code and has a response like `noty("1603984008730.torrent - "+theUILang.addTorrentSuccess,"success");`. this code is btw evaluated in the original ruTorrent ui and spawns a notification toast in the lower right-hand corner, notifying the user of success. this is missing from your install - there's no feedback that a torrent was added (or not).

the confusing part is that for me, even using RTA, i don't get `result[]=FailedFile` chunks in the redirect url - it's `Success` all the way - as it should be if adding the file actually works. so *that* part i'm not able to reproduce.

in summation, this is clearly a faulty setup on your(/swizzin's) end. perhaps it's worth opening an issue with them and describing what exactly is broken in ruTorrent. a link to the aforementioned code line together with this screenshot showing the omission of the relative path should give enough indicators for one of their guys to get to the root cause of this problem. :)
![image](https://user-images.githubusercontent.com/1835496/97595873-6dd81080-1a04-11eb-8a41-d28785ef4f5c.png)

in either case, i don't see a reasonable way of ignoring the 404 request without also sacrificing error detection for wrong configuration inputs. a 404 code usually indicates an incorrect configuration for host or relative path and must not be ignored. so this is not fixable on RTA's end.

**Comment by Nico83500** [comment]
Thank you very much for analysis, I'll open an issue. I'm going to try another ruTorrent install.

**Comment by liaralabs** [comment]
Thanks for the detailed work here guys, definitely gave me a starting point to look for the issue. I'll leave some notes here in the event that anyone stumbles across the issue in the future.

By default swizzin uses the distro snippet for `fastcgi-php.conf` which sets a few standard things and attempts to help workaround some configuration errors by attempting to split the PHP path and pass it back to fastcgi. There are some rather severe vulnerabilities for clients like Nextcloud which need this fix, hence why it is important to keep in most cases.

Funnily enough, the line (`$location=`) that was mentioned is the exact line which broke the implementation. This line was altered in April and I'm assuming this is when the breakage began (https://github.com/Novik/ruTorrent/commit/345dbe58a892f1d05b7e6235d630b0bb6741229e#diff-7c393f69e7911ccd1d0f7a5a0f4d07c93d946eda2772e391ee16716c205c00b4)

The fix here is to disable the distro snippet and specify custom rules for the ruTorrent location.

Specifically, these lines are the problematic ones which are essentially nulling out the PATH_INFO variable:

```
# Bypass the fact that try_files resets $fastcgi_path_info
# see: http://trac.nginx.org/nginx/ticket/321
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;
```

If we don't pass these to ruTorrent, then everything behaves as normal.

I don't know why ruTorrent addtorrent.php doesn't play well with this param, that's a question for someone else. The ruTorrent configuration appears to have been working fine (including adding torrents) whilst using the WebUI and not accessing endpoints directly.

**Comment by Nico83500** [comment]
It works, thank you !

**Comment by Fogest** [comment]
@liaralabs Just to clarify what is the fix here? I am not good with the configuration of things like rutorrent which is one of the reasons I chose Swizzin so I apologise for my ignorance. 

Is there a fix that will come out in Swizzin and I could just wait for the proper changes through those channels? This bug isn't too much of an issue for me as it does still work, just gives the wrong message back.

**Comment by liaralabs** [comment]
The follow up for swizzin specifically is in the issue that nico created in the swizzin repo. It's linked just above my first post in this issue.

**Comment by Fogest** [comment]
@liaralabs Ah I see, I did `box update` and got the latest changes and it did fix the problem for me as well. Thank you!
