### ISSUE TITLE
rTorrent XML-RPC Type does not send requests

### ISSUE THREAD

**Issue by Abbotta4** [bogenpirat/remote-torrent-adder#306]
I am trying to configure remote torrent adder to add torrents to rtorrent using the xmlrpc interface, but the nginx logs show that no access is made when I try to add a torrent. My nginx config for rtorrent is:
```
server {
    listen   6000;
    listen   [::]:6000;
    error_log /var/log/nginx/rt-nginx-err.log;
    location /RPC2 {
        include scgi_params;
        scgi_pass unix:/srv/rtorrent/.scgi_local;
    }
}
```
and in my main `/etc/nginx/nginx.conf` I have
```
http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
...
}
```
I can see that this interface is up and working with a test curl command:
```
user@host% curl "10.244.1.238:6000/RPC2"
```
yields
```
user@host% sudo tail -f access.log
10.244.1.238 - - [05/May/2021:13:04:20 -0500] "GET /RPC2 HTTP/1.1" 502 150 "-" "curl/7.76.0" "-"
```
but if I try to add a torrent with remote torrent adder, I do not see a logged access. Remote torrent adder fails and the notification error says
"Failure
Could not contact rt
Error: failed to fetch"

**Comment by bogenpirat** [comment]
been a while since i looked at #282 which added this, but judging from [the code](https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/rtorrentXmlRpc.js#L29), just confirming that your settings in RTA are, `10.244.1.238` as server, `6000` as port and `RPC2` as relative path?

if this isn't a firewall issue, you might want to check out the extension's dev tools window you can reach from `chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci` by clicking on `background page` under inspect views. once there, switch to the network tab, then try adding a torrent. you'll be able to take a look at what request URL RTA constructed out of your config and, if necessary, figure out a reproduction case.
