### ISSUE TITLE
Deluge only work with default user

### ISSUE THREAD

**Issue by JamesDAdams** [bogenpirat/remote-torrent-adder#330]
Hi,

on my deluge i have multiple user in auth :
```
localclient:363135bf4d52b91dd4e29a6476e59f8cb3371a59:10
JamesAdamsManual:password:5
JamesAdamsTemp:password:10
```

Bu with the chrome extension it's only work with the default (localclient) not the other

**Comment by bogenpirat** [comment]
this likely occurs due to the way in which chrome sends credentials; login credentials are stored locally in the browser's session and are only overwritten from requests when the server requests authentication. this is the case if the auth in the session is rejected, or if there is none. this authentication persists between requests, both manual ones as well as those authored by an extension.

in the context of RTA, that means: if you're logged into your web interface manually, that account will be used for RTA's requests. if you're not logged into your web interface, RTA will initiate the authentication and the browser will retain that information.

to my knowledge, the only feasible way of resetting this session authentication data is to restart chrome, or open an incognito tab. hence, switching between webui accounts by way of RTA doesn't seem feasible.
